# fly.toml app configuration file generated for damp-thunder-6671 on 2023-05-01T09:27:49-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "damp-thunder-6671"
primary_region = "bos"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
